
ALTER TABLE `games`
	CHANGE COLUMN `green` `greenId` INT(11) NULL DEFAULT NULL,
	CHANGE COLUMN `yellow` `yellowId` INT(11) NULL DEFAULT NULL,
	CHANGE COLUMN `blue` `blueId` INT(11) NULL DEFAULT NULL,
	CHANGE COLUMN `red` `redId` INT(11) NULL DEFAULT NULL;
