
CREATE TABLE `matches` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`matchType` VARCHAR(10) NULL DEFAULT NULL,
	`playTo` INT(11) NULL DEFAULT NULL,
	`numOfGames` INT(11) NULL DEFAULT NULL,
	`game` INT(11) NULL DEFAULT NULL,
	`ready` INT(11) NULL DEFAULT NULL,
	`complete` INT(11) NULL DEFAULT NULL,
	`createdAt` DATETIME NULL DEFAULT NULL,
	`modifiedAt` DATETIME NULL DEFAULT NULL,
	`completedAt` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
