
CREATE TABLE `isms` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`left` INT(11) NULL DEFAULT NULL,
	`right` INT(11) NULL DEFAULT NULL,
	`saying` VARCHAR(255) NULL DEFAULT NULL,
	`approved` TINYINT(4) NULL DEFAULT NULL,
	`createdAt` DATETIME NULL DEFAULT NULL,
	`modifiedAt` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
